### ISSUE TITLE
RAT vs equally weighted strategy

### ISSUE THREAD

**Issue by turmeric-blend** [Ivsxk/RAT#3]
hi, I was wondering, is RAT tested against an equally-weighted strategy? For example equally-weighted on S&P500 vs RAT on S&P500

**Comment by Ivsxk** [comment]
The results of an equally-weighted strategy for Crypto-A:
APV:2.51 | SR: 4.29 | CR: 6.94
The results of an equally-weighted strategy for S&P500:
APV: 1.21 | SR: 11.88 | CR: 13.63
