### ISSUE TITLE
Question on 'previous action' implementation

### ISSUE THREAD

**Issue by turmeric-blend** [Ivsxk/RAT#4]
Hi I have a question on the 'previous action' functionality implementation in the code. I might be wrong but it seems like you are sampling the previous action from `self.__PVM`. Every time a new batch is sampled, [this](https://github.com/Ivsxk/RAT/blob/563d9a93836e3462482182ec93e4aa21ec67dc54/main.py#L474) function gets called. From the code I can see `self.__PVM` is initialized [here](https://github.com/Ivsxk/RAT/blob/563d9a93836e3462482182ec93e4aa21ec67dc54/main.py#L369).

The question:

However, it seems like the order of sampling previous actions for the RAT network is 
1. `batch=DM.next_batch()` --> when next batch called
2. `last_w = self.__PVM.values[indexs-1, :]` --> sample 'previous action' and return as `last_w` using random starting index (say index A)
3. reshape 'previous action' as `previous_w`
```
previous_w=torch.tensor(batch_last_w,dtype=torch.float).to(device)
previous_w=torch.unsqueeze(previous_w,1)
```
4. `out = model.forward(src, currt_price, previous_w, price_series_mask, trg_mask, padding_price)` --> passing `previous_w` to RAT model
5. setting 'new action' to the **same** index A in `self.__PVM`
```
 def setw(w):
        self.__PVM.iloc[indexs, :] = w
```
6. repeat by sampling from a new random starting index (say index B).

in this sense, the RAT model is **not** really receiving a 'previous action' due to the different starting index. Moreover, it is just receiving the [initialization](https://github.com/Ivsxk/RAT/blob/563d9a93836e3462482182ec93e4aa21ec67dc54/main.py#L369).

I might have missed something, but any clarification on this is appreciated! :)

**Comment by Ivsxk** [comment]
![image](https://user-images.githubusercontent.com/32444800/91385225-fd294200-e862-11ea-8fc0-1e5e30ea0945.png)

**Comment by turmeric-blend** [comment]
Hi @Ivsxk, if I understand it correctly, then setting **previous_w to a random** distribution (eg for 3 assets including cash, [0.5, 0.3, 0.2] - random numbers) at every batch (iteration) during training would be a viable option as well since every batch is independent compared to the previous. Of course, this would require a change to how rewards are calculated in terms of code. This would be conceptually the same but with a lighter computation compared to sampling from a PVM matrix. What do you think?

**Comment by Ivsxk** [comment]
Hi @turmeric-blend, of course you can set previous_w to a random distribution. But reading previous_w from the self.PVM helps saving transaction costs, by keeping a small difference between the new w and previous_w. (The previous_w does not correspond to the previous batch, but corresponds to the previous trading period.)  Section 5.2 in "A deep reinforcement learning framework for the financial portfolio management problem." gives a detailed description of self.PVM.

**Comment by turmeric-blend** [comment]
from section 5.2,

> Sharing a single memory stack allows a network to be trained simultaneously against data points within a mini-batches, enormously improving training efficiency.

In my opinion sampling from PVM doesn't really 'improve training efficiency' and is no different than random distribution as the so called 'previous_w' would change over time as well as new 'w' are inserted into the indexes. Having said that I think its more natural to think of the agent acting on 'previous_w' as: **given a particular distribution (random or not) and a certain price history, how should we re-distribute the portfolio to maximize its value**.

Anyway this is just my humble opinion and thought I just point it out as an idea.
